[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"server/main.py" = ["E402"]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:pkg_resources is deprecated as an API:UserWarning:opentelemetry.instrumentation.dependencies",
]
